/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class bags : bagsBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/bags.def
	public abstract class bagsBase : EntityComponent
	{
		public EntityBaseEntityCall_bagsBase baseEntityCall = null;
		public EntityCellEntityCall_bagsBase cellEntityCall = null;


		public abstract void onAddItem(ITEM_INFO arg1); 
		public abstract void onBags(List<ITEM_INFO> arg1); 
		public abstract void onBuyItem(string arg1, ITEM_INFO arg2); 
		public abstract void onDelItem(ITEM_INFO arg1); 
		public abstract void onRecharge(string arg1, Int32 arg2, Int32 arg3); 
		public abstract void onRechargeOrder(string arg1); 

		public override void createFromStream(MemoryStream stream)
		{
			base.createFromStream(stream);
			baseEntityCall = new EntityBaseEntityCall_bagsBase(entityComponentPropertyID, ownerID);
			cellEntityCall = new EntityCellEntityCall_bagsBase(entityComponentPropertyID, ownerID);
		}

		public override void onRemoteMethodCall(UInt16 methodUtype, MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["bags"];

			Method method = sm.idmethods[methodUtype];
			switch(method.methodUtype)
			{
				case 53:
					ITEM_INFO onAddItem_arg1 = ((DATATYPE_ITEM_INFO)method.args[0]).createFromStreamEx(stream);
					onAddItem(onAddItem_arg1);
					break;
				case 51:
					List<ITEM_INFO> onBags_arg1 = ((DATATYPE_AnonymousArray_62)method.args[0]).createFromStreamEx(stream);
					onBags(onBags_arg1);
					break;
				case 52:
					string onBuyItem_arg1 = stream.readUnicode();
					ITEM_INFO onBuyItem_arg2 = ((DATATYPE_ITEM_INFO)method.args[1]).createFromStreamEx(stream);
					onBuyItem(onBuyItem_arg1, onBuyItem_arg2);
					break;
				case 54:
					ITEM_INFO onDelItem_arg1 = ((DATATYPE_ITEM_INFO)method.args[0]).createFromStreamEx(stream);
					onDelItem(onDelItem_arg1);
					break;
				case 56:
					string onRecharge_arg1 = stream.readUnicode();
					Int32 onRecharge_arg2 = stream.readInt32();
					Int32 onRecharge_arg3 = stream.readInt32();
					onRecharge(onRecharge_arg1, onRecharge_arg2, onRecharge_arg3);
					break;
				case 55:
					string onRechargeOrder_arg1 = stream.readUnicode();
					onRechargeOrder(onRechargeOrder_arg1);
					break;
				default:
					break;
			};
		}

		public override void onUpdatePropertys(UInt16 propUtype, MemoryStream stream, int maxCount)
		{
			ScriptModule sm = EntityDef.moduledefs["bags"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0 && maxCount-- != 0)
			{
				UInt16 _t_utype = 0;
				UInt16 _t_child_utype = propUtype;

				if(_t_child_utype == 0)
				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
						_t_child_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
						_t_child_utype = stream.readUint16();
					}
				}

				Property prop = null;

				prop = pdatas[_t_child_utype];

				switch(prop.properUtype)
				{
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["bags"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

		}
	}
}