/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Account.def
	public class EntityBaseEntityCall_AccountBase : EntityCall
	{
		public EntityBaseEntityCall_FriendsBase Friends = null;
		public EntityBaseEntityCall_LandBase Land = null;
		public EntityBaseEntityCall_PetBase Pet = null;
		public EntityBaseEntityCall_TaskBase Task = null;
		public EntityBaseEntityCall_bagsBase bags = null;

		public EntityBaseEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			Friends = new EntityBaseEntityCall_FriendsBase(10, id);
			Land = new EntityBaseEntityCall_LandBase(7, id);
			Pet = new EntityBaseEntityCall_PetBase(17, id);
			Task = new EntityBaseEntityCall_TaskBase(20, id);
			bags = new EntityBaseEntityCall_bagsBase(5, id);
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void reqAccountCardData()
		{
			Bundle pBundle = newCall("reqAccountCardData", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqAvatarList()
		{
			Bundle pBundle = newCall("reqAvatarList", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqBindAccount(string arg1, string arg2)
		{
			Bundle pBundle = newCall("reqBindAccount", 0);
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			bundle.writeUnicode(arg2);
			sendCall(null);
		}

		public void reqBuyWithGold(Int64 arg1)
		{
			Bundle pBundle = newCall("reqBuyWithGold", 0);
			if(pBundle == null)
				return;

			bundle.writeInt64(arg1);
			sendCall(null);
		}

		public void reqBuyWithRMB(Int64 arg1)
		{
			Bundle pBundle = newCall("reqBuyWithRMB", 0);
			if(pBundle == null)
				return;

			bundle.writeInt64(arg1);
			sendCall(null);
		}

		public void reqChangeAvatar(SByte arg1, AVATAR_CARDLIST arg2, string arg3, SByte arg4)
		{
			Bundle pBundle = newCall("reqChangeAvatar", 0);
			if(pBundle == null)
				return;

			bundle.writeInt8(arg1);
			((DATATYPE_AVATAR_CARDLIST)EntityDef.id2datatypes[26]).addToStreamEx(bundle, arg2);
			bundle.writeUnicode(arg3);
			bundle.writeInt8(arg4);
			sendCall(null);
		}

		public void reqChangeData(string arg1, Byte arg2, UInt32 arg3)
		{
			Bundle pBundle = newCall("reqChangeData", 0);
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			bundle.writeUint8(arg2);
			bundle.writeUint32(arg3);
			sendCall(null);
		}

		public void reqData(UInt64 arg1)
		{
			Bundle pBundle = newCall("reqData", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			sendCall(null);
		}

		public void reqGetClient()
		{
			Bundle pBundle = newCall("reqGetClient", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqHasEnteredBattlefiled()
		{
			Bundle pBundle = newCall("reqHasEnteredBattlefiled", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqInf()
		{
			Bundle pBundle = newCall("reqInf", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqMoney()
		{
			Bundle pBundle = newCall("reqMoney", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqOpeningPack()
		{
			Bundle pBundle = newCall("reqOpeningPack", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqPlayerSum()
		{
			Bundle pBundle = newCall("reqPlayerSum", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqRemoveAvatar(Byte arg1)
		{
			Bundle pBundle = newCall("reqRemoveAvatar", 0);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			sendCall(null);
		}

		public void reqStartMarch(Int16 arg1)
		{
			Bundle pBundle = newCall("reqStartMarch", 0);
			if(pBundle == null)
				return;

			bundle.writeInt16(arg1);
			sendCall(null);
		}

		public void reqStopMarch()
		{
			Bundle pBundle = newCall("reqStopMarch", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AccountBase : EntityCall
	{
		public EntityCellEntityCall_FriendsBase Friends = null;
		public EntityCellEntityCall_LandBase Land = null;
		public EntityCellEntityCall_PetBase Pet = null;
		public EntityCellEntityCall_TaskBase Task = null;
		public EntityCellEntityCall_bagsBase bags = null;

		public EntityCellEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			Friends = new EntityCellEntityCall_FriendsBase(10, id);
			Land = new EntityCellEntityCall_LandBase(7, id);
			Pet = new EntityCellEntityCall_PetBase(17, id);
			Task = new EntityCellEntityCall_TaskBase(20, id);
			bags = new EntityCellEntityCall_bagsBase(5, id);
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
