/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avatar.def
	public class EntityBaseEntityCall_AvatarBase : EntityCall
	{

		public EntityBaseEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_AvatarBase : EntityCall
	{

		public EntityCellEntityCall_AvatarBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void onBeginChooseCard(ENTITY_ID_LIST arg1)
		{
			Bundle pBundle = newCall("onBeginChooseCard", 0);
			if(pBundle == null)
				return;

			((DATATYPE_ENTITY_ID_LIST)EntityDef.id2datatypes[25]).addToStreamEx(bundle, arg1);
			sendCall(null);
		}

		public void reqAtt(Int32 arg1)
		{
			Bundle pBundle = newCall("reqAtt", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

		public void reqChoose(Int32 arg1)
		{
			Bundle pBundle = newCall("reqChoose", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

		public void reqEndRound()
		{
			Bundle pBundle = newCall("reqEndRound", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqGiveUp()
		{
			Bundle pBundle = newCall("reqGiveUp", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqSendDialog(string arg1, string arg2)
		{
			Bundle pBundle = newCall("reqSendDialog", 0);
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			bundle.writeUnicode(arg2);
			sendCall(null);
		}

		public void reqUse(Int32 arg1, SByte arg2)
		{
			Bundle pBundle = newCall("reqUse", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			bundle.writeInt8(arg2);
			sendCall(null);
		}

		public void testAddTime()
		{
			Bundle pBundle = newCall("testAddTime", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void testChangeSkill(Byte arg1)
		{
			Bundle pBundle = newCall("testChangeSkill", 0);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			sendCall(null);
		}

		public void testGetCard(UInt32 arg1)
		{
			Bundle pBundle = newCall("testGetCard", 0);
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			sendCall(null);
		}

		public void testMaxCrystal()
		{
			Bundle pBundle = newCall("testMaxCrystal", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

	}
	}
