/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/card.def
	public class EntityBaseEntityCall_cardBase : EntityCall
	{

		public EntityBaseEntityCall_cardBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_cardBase : EntityCall
	{

		public EntityCellEntityCall_cardBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void reqAtt(Int32 arg1)
		{
			Bundle pBundle = newCall("reqAtt", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

		public void reqChoose(Int32 arg1)
		{
			Bundle pBundle = newCall("reqChoose", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

		public void reqUse(Int32 arg1, SByte arg2)
		{
			Bundle pBundle = newCall("reqUse", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			bundle.writeInt8(arg2);
			sendCall(null);
		}

	}
	}
