/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Land.def
	public class EntityBaseEntityCall_LandBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityBaseEntityCall_LandBase(UInt16 ecpID, Int32 eid) : base(eid, "Land")
		{
			entityComponentPropertyID = ecpID;
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void reqAllLandInfo(UInt64 arg1)
		{
			Bundle pBundle = newCall("reqAllLandInfo", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			sendCall(null);
		}

		public void reqBuyLand(UInt64 arg1, UInt32 arg2)
		{
			Bundle pBundle = newCall("reqBuyLand", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			bundle.writeUint32(arg2);
			sendCall(null);
		}

		public void reqGJInfo()
		{
			Bundle pBundle = newCall("reqGJInfo", entityComponentPropertyID);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqGiveLand(UInt32 arg1, UInt32 arg2)
		{
			Bundle pBundle = newCall("reqGiveLand", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			bundle.writeUint32(arg2);
			sendCall(null);
		}

		public void reqLandInfo(UInt32 arg1)
		{
			Bundle pBundle = newCall("reqLandInfo", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			sendCall(null);
		}

		public void reqPlant(UInt32 arg1, UInt32 arg2)
		{
			Bundle pBundle = newCall("reqPlant", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			bundle.writeUint32(arg2);
			sendCall(null);
		}

		public void reqfertilization(UInt32 arg1, UInt32 arg2, UInt32 arg3)
		{
			Bundle pBundle = newCall("reqfertilization", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			bundle.writeUint32(arg2);
			bundle.writeUint32(arg3);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_LandBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityCellEntityCall_LandBase(UInt16 ecpID, Int32 eid) : base(eid, "Land")
		{
			entityComponentPropertyID = ecpID;
			className = "Land";
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
