/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/bags.def
	public class EntityBaseEntityCall_bagsBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityBaseEntityCall_bagsBase(UInt16 ecpID, Int32 eid) : base(eid, "bags")
		{
			entityComponentPropertyID = ecpID;
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void reqBags()
		{
			Bundle pBundle = newCall("reqBags", entityComponentPropertyID);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqBuyItem(Int32 arg1, Int32 arg2)
		{
			Bundle pBundle = newCall("reqBuyItem", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			bundle.writeInt32(arg2);
			sendCall(null);
		}

		public void reqRechargeOrder(Int32 arg1, Int32 arg2)
		{
			Bundle pBundle = newCall("reqRechargeOrder", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			bundle.writeInt32(arg2);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_bagsBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityCellEntityCall_bagsBase(UInt16 ecpID, Int32 eid) : base(eid, "bags")
		{
			entityComponentPropertyID = ecpID;
			className = "bags";
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
