/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Pet.def
	public class EntityBaseEntityCall_PetBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityBaseEntityCall_PetBase(UInt16 ecpID, Int32 eid) : base(eid, "Pet")
		{
			entityComponentPropertyID = ecpID;
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void reqAllPetInfo(UInt64 arg1)
		{
			Bundle pBundle = newCall("reqAllPetInfo", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			sendCall(null);
		}

		public void reqCatchPet(string arg1, UInt32 arg2, UInt32 arg3)
		{
			Bundle pBundle = newCall("reqCatchPet", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			bundle.writeUint32(arg2);
			bundle.writeUint32(arg3);
			sendCall(null);
		}

		public void reqPetCompound()
		{
			Bundle pBundle = newCall("reqPetCompound", entityComponentPropertyID);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqPetHarvest(UInt64 arg1)
		{
			Bundle pBundle = newCall("reqPetHarvest", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			sendCall(null);
		}

		public void reqPetMapInfo(string arg1)
		{
			Bundle pBundle = newCall("reqPetMapInfo", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			sendCall(null);
		}

		public void reqPetSelfInfo()
		{
			Bundle pBundle = newCall("reqPetSelfInfo", entityComponentPropertyID);
			if(pBundle == null)
				return;

			sendCall(null);
		}

	}

	public class EntityCellEntityCall_PetBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityCellEntityCall_PetBase(UInt16 ecpID, Int32 eid) : base(eid, "Pet")
		{
			entityComponentPropertyID = ecpID;
			className = "Pet";
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
