/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Task.def
	public class EntityBaseEntityCall_TaskBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityBaseEntityCall_TaskBase(UInt16 ecpID, Int32 eid) : base(eid, "Task")
		{
			entityComponentPropertyID = ecpID;
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void reqFinishTask(UInt32 arg1)
		{
			Bundle pBundle = newCall("reqFinishTask", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			sendCall(null);
		}

		public void reqTaskAward(UInt32 arg1, UInt32 arg2)
		{
			Bundle pBundle = newCall("reqTaskAward", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			bundle.writeUint32(arg2);
			sendCall(null);
		}

		public void reqTaskList()
		{
			Bundle pBundle = newCall("reqTaskList", entityComponentPropertyID);
			if(pBundle == null)
				return;

			sendCall(null);
		}

	}

	public class EntityCellEntityCall_TaskBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityCellEntityCall_TaskBase(UInt16 ecpID, Int32 eid) : base(eid, "Task")
		{
			entityComponentPropertyID = ecpID;
			className = "Task";
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
