/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Friends : FriendsBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Friends.def
	public abstract class FriendsBase : EntityComponent
	{
		public EntityBaseEntityCall_FriendsBase baseEntityCall = null;
		public EntityCellEntityCall_FriendsBase cellEntityCall = null;


		public abstract void onAcceptYaoShu(string arg1); 
		public abstract void onAllSysMessage(string arg1, List<SYS_MESSAGE> arg2); 
		public abstract void onApplyYaoShu(string arg1); 
		public abstract void onCheckCanSteal(List<CAN_STEAL_INFO> arg1, UInt64 arg2); 
		public abstract void onCheckMessageCanSteal(Byte arg1, UInt64 arg2); 
		public abstract void onFriendList(List<FRIEND_INFO> arg1); 
		public abstract void onOpenFriendList(string arg1); 
		public abstract void onReadMessage(UInt32 arg1); 
		public abstract void onSteal(string arg1, List<STEAL_INFO> arg2); 
		public abstract void onSysMessage(SYS_MESSAGE arg1); 
		public abstract void onYaoShu(string arg1); 
		public abstract void onYaoShuStatus(List<APPLY_INFO> arg1, List<ACCEPT_INFO> arg2, UInt64 arg3); 

		public override void createFromStream(MemoryStream stream)
		{
			base.createFromStream(stream);
			baseEntityCall = new EntityBaseEntityCall_FriendsBase(entityComponentPropertyID, ownerID);
			cellEntityCall = new EntityCellEntityCall_FriendsBase(entityComponentPropertyID, ownerID);
		}

		public override void onRemoteMethodCall(UInt16 methodUtype, MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Friends"];

			Method method = sm.idmethods[methodUtype];
			switch(method.methodUtype)
			{
				case 89:
					string onAcceptYaoShu_arg1 = stream.readUnicode();
					onAcceptYaoShu(onAcceptYaoShu_arg1);
					break;
				case 91:
					string onAllSysMessage_arg1 = stream.readUnicode();
					List<SYS_MESSAGE> onAllSysMessage_arg2 = ((DATATYPE_AnonymousArray_73)method.args[1]).createFromStreamEx(stream);
					onAllSysMessage(onAllSysMessage_arg1, onAllSysMessage_arg2);
					break;
				case 88:
					string onApplyYaoShu_arg1 = stream.readUnicode();
					onApplyYaoShu(onApplyYaoShu_arg1);
					break;
				case 95:
					List<CAN_STEAL_INFO> onCheckCanSteal_arg1 = ((DATATYPE_AnonymousArray_75)method.args[0]).createFromStreamEx(stream);
					UInt64 onCheckCanSteal_arg2 = stream.readUint64();
					onCheckCanSteal(onCheckCanSteal_arg1, onCheckCanSteal_arg2);
					break;
				case 96:
					Byte onCheckMessageCanSteal_arg1 = stream.readUint8();
					UInt64 onCheckMessageCanSteal_arg2 = stream.readUint64();
					onCheckMessageCanSteal(onCheckMessageCanSteal_arg1, onCheckMessageCanSteal_arg2);
					break;
				case 86:
					List<FRIEND_INFO> onFriendList_arg1 = ((DATATYPE_AnonymousArray_70)method.args[0]).createFromStreamEx(stream);
					onFriendList(onFriendList_arg1);
					break;
				case 97:
					string onOpenFriendList_arg1 = stream.readUnicode();
					onOpenFriendList(onOpenFriendList_arg1);
					break;
				case 93:
					UInt32 onReadMessage_arg1 = stream.readUint32();
					onReadMessage(onReadMessage_arg1);
					break;
				case 94:
					string onSteal_arg1 = stream.readUnicode();
					List<STEAL_INFO> onSteal_arg2 = ((DATATYPE_AnonymousArray_74)method.args[1]).createFromStreamEx(stream);
					onSteal(onSteal_arg1, onSteal_arg2);
					break;
				case 92:
					SYS_MESSAGE onSysMessage_arg1 = ((DATATYPE_SYS_MESSAGE)method.args[0]).createFromStreamEx(stream);
					onSysMessage(onSysMessage_arg1);
					break;
				case 90:
					string onYaoShu_arg1 = stream.readUnicode();
					onYaoShu(onYaoShu_arg1);
					break;
				case 87:
					List<APPLY_INFO> onYaoShuStatus_arg1 = ((DATATYPE_AnonymousArray_71)method.args[0]).createFromStreamEx(stream);
					List<ACCEPT_INFO> onYaoShuStatus_arg2 = ((DATATYPE_AnonymousArray_72)method.args[1]).createFromStreamEx(stream);
					UInt64 onYaoShuStatus_arg3 = stream.readUint64();
					onYaoShuStatus(onYaoShuStatus_arg1, onYaoShuStatus_arg2, onYaoShuStatus_arg3);
					break;
				default:
					break;
			};
		}

		public override void onUpdatePropertys(UInt16 propUtype, MemoryStream stream, int maxCount)
		{
			ScriptModule sm = EntityDef.moduledefs["Friends"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0 && maxCount-- != 0)
			{
				UInt16 _t_utype = 0;
				UInt16 _t_child_utype = propUtype;

				if(_t_child_utype == 0)
				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
						_t_child_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
						_t_child_utype = stream.readUint16();
					}
				}

				Property prop = null;

				prop = pdatas[_t_child_utype];

				switch(prop.properUtype)
				{
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["Friends"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

		}
	}
}