/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;



	// defined in */scripts/entity_defs/types.xml

	public struct UINT8
	{
		Byte value;

		UINT8(Byte value)
		{
			this.value = value;
		}

		public static implicit operator Byte(UINT8 value)
		{
			return value.value;
		}

		public static implicit operator UINT8(Byte value)
		{
			Byte tvalue = (Byte)value;
			return new UINT8(tvalue);
		}

		public static Byte MaxValue
		{
			get
			{
				return Byte.MaxValue;
			}
		}

		public static Byte MinValue
		{
			get
			{
				return Byte.MinValue;
			}
		}
	}

	public struct UINT16
	{
		UInt16 value;

		UINT16(UInt16 value)
		{
			this.value = value;
		}

		public static implicit operator UInt16(UINT16 value)
		{
			return value.value;
		}

		public static implicit operator UINT16(UInt16 value)
		{
			UInt16 tvalue = (UInt16)value;
			return new UINT16(tvalue);
		}

		public static UInt16 MaxValue
		{
			get
			{
				return UInt16.MaxValue;
			}
		}

		public static UInt16 MinValue
		{
			get
			{
				return UInt16.MinValue;
			}
		}
	}

	public struct UINT64
	{
		UInt64 value;

		UINT64(UInt64 value)
		{
			this.value = value;
		}

		public static implicit operator UInt64(UINT64 value)
		{
			return value.value;
		}

		public static implicit operator UINT64(UInt64 value)
		{
			UInt64 tvalue = (UInt64)value;
			return new UINT64(tvalue);
		}

		public static UInt64 MaxValue
		{
			get
			{
				return UInt64.MaxValue;
			}
		}

		public static UInt64 MinValue
		{
			get
			{
				return UInt64.MinValue;
			}
		}
	}

	public struct UINT32
	{
		UInt32 value;

		UINT32(UInt32 value)
		{
			this.value = value;
		}

		public static implicit operator UInt32(UINT32 value)
		{
			return value.value;
		}

		public static implicit operator UINT32(UInt32 value)
		{
			UInt32 tvalue = (UInt32)value;
			return new UINT32(tvalue);
		}

		public static UInt32 MaxValue
		{
			get
			{
				return UInt32.MaxValue;
			}
		}

		public static UInt32 MinValue
		{
			get
			{
				return UInt32.MinValue;
			}
		}
	}

	public struct INT8
	{
		SByte value;

		INT8(SByte value)
		{
			this.value = value;
		}

		public static implicit operator SByte(INT8 value)
		{
			return value.value;
		}

		public static implicit operator INT8(SByte value)
		{
			SByte tvalue = (SByte)value;
			return new INT8(tvalue);
		}

		public static SByte MaxValue
		{
			get
			{
				return SByte.MaxValue;
			}
		}

		public static SByte MinValue
		{
			get
			{
				return SByte.MinValue;
			}
		}
	}

	public struct INT16
	{
		Int16 value;

		INT16(Int16 value)
		{
			this.value = value;
		}

		public static implicit operator Int16(INT16 value)
		{
			return value.value;
		}

		public static implicit operator INT16(Int16 value)
		{
			Int16 tvalue = (Int16)value;
			return new INT16(tvalue);
		}

		public static Int16 MaxValue
		{
			get
			{
				return Int16.MaxValue;
			}
		}

		public static Int16 MinValue
		{
			get
			{
				return Int16.MinValue;
			}
		}
	}

	public struct INT32
	{
		Int32 value;

		INT32(Int32 value)
		{
			this.value = value;
		}

		public static implicit operator Int32(INT32 value)
		{
			return value.value;
		}

		public static implicit operator INT32(Int32 value)
		{
			Int32 tvalue = (Int32)value;
			return new INT32(tvalue);
		}

		public static Int32 MaxValue
		{
			get
			{
				return Int32.MaxValue;
			}
		}

		public static Int32 MinValue
		{
			get
			{
				return Int32.MinValue;
			}
		}
	}

	public struct INT64
	{
		Int64 value;

		INT64(Int64 value)
		{
			this.value = value;
		}

		public static implicit operator Int64(INT64 value)
		{
			return value.value;
		}

		public static implicit operator INT64(Int64 value)
		{
			Int64 tvalue = (Int64)value;
			return new INT64(tvalue);
		}

		public static Int64 MaxValue
		{
			get
			{
				return Int64.MaxValue;
			}
		}

		public static Int64 MinValue
		{
			get
			{
				return Int64.MinValue;
			}
		}
	}

	public struct STRING
	{
		string value;

		STRING(string value)
		{
			this.value = value;
		}

		public static implicit operator string(STRING value)
		{
			return value.value;
		}

		public static implicit operator STRING(string value)
		{
			string tvalue = (string)value;
			return new STRING(tvalue);
		}
	}

	public struct UNICODE
	{
		string value;

		UNICODE(string value)
		{
			this.value = value;
		}

		public static implicit operator string(UNICODE value)
		{
			return value.value;
		}

		public static implicit operator UNICODE(string value)
		{
			string tvalue = (string)value;
			return new UNICODE(tvalue);
		}
	}

	public struct FLOAT
	{
		float value;

		FLOAT(float value)
		{
			this.value = value;
		}

		public static implicit operator float(FLOAT value)
		{
			return value.value;
		}

		public static implicit operator FLOAT(float value)
		{
			float tvalue = (float)value;
			return new FLOAT(tvalue);
		}

		public static float MaxValue
		{
			get
			{
				return float.MaxValue;
			}
		}

		public static float MinValue
		{
			get
			{
				return float.MinValue;
			}
		}
	}

	public struct DOUBLE
	{
		double value;

		DOUBLE(double value)
		{
			this.value = value;
		}

		public static implicit operator double(DOUBLE value)
		{
			return value.value;
		}

		public static implicit operator DOUBLE(double value)
		{
			double tvalue = (double)value;
			return new DOUBLE(tvalue);
		}

		public static double MaxValue
		{
			get
			{
				return double.MaxValue;
			}
		}

		public static double MinValue
		{
			get
			{
				return double.MinValue;
			}
		}
	}

	public struct PYTHON
	{
		byte[] value;

		PYTHON(byte[] value)
		{
			this.value = value;
		}

		public static implicit operator byte[](PYTHON value)
		{
			return value.value;
		}

		public static implicit operator PYTHON(byte[] value)
		{
			byte[] tvalue = (byte[])value;
			return new PYTHON(tvalue);
		}

		public Byte this[int ID]
		{
			get { return value[ID]; }
			set { this.value[ID] = value; }
		}
	}

	public struct PY_DICT
	{
		byte[] value;

		PY_DICT(byte[] value)
		{
			this.value = value;
		}

		public static implicit operator byte[](PY_DICT value)
		{
			return value.value;
		}

		public static implicit operator PY_DICT(byte[] value)
		{
			byte[] tvalue = (byte[])value;
			return new PY_DICT(tvalue);
		}

		public Byte this[int ID]
		{
			get { return value[ID]; }
			set { this.value[ID] = value; }
		}
	}

	public struct PY_TUPLE
	{
		byte[] value;

		PY_TUPLE(byte[] value)
		{
			this.value = value;
		}

		public static implicit operator byte[](PY_TUPLE value)
		{
			return value.value;
		}

		public static implicit operator PY_TUPLE(byte[] value)
		{
			byte[] tvalue = (byte[])value;
			return new PY_TUPLE(tvalue);
		}

		public Byte this[int ID]
		{
			get { return value[ID]; }
			set { this.value[ID] = value; }
		}
	}

	public struct PY_LIST
	{
		byte[] value;

		PY_LIST(byte[] value)
		{
			this.value = value;
		}

		public static implicit operator byte[](PY_LIST value)
		{
			return value.value;
		}

		public static implicit operator PY_LIST(byte[] value)
		{
			byte[] tvalue = (byte[])value;
			return new PY_LIST(tvalue);
		}

		public Byte this[int ID]
		{
			get { return value[ID]; }
			set { this.value[ID] = value; }
		}
	}

	public struct ENTITYCALL
	{
		byte[] value;

		ENTITYCALL(byte[] value)
		{
			this.value = value;
		}

		public static implicit operator byte[](ENTITYCALL value)
		{
			return value.value;
		}

		public static implicit operator ENTITYCALL(byte[] value)
		{
			byte[] tvalue = (byte[])value;
			return new ENTITYCALL(tvalue);
		}

		public Byte this[int ID]
		{
			get { return value[ID]; }
			set { this.value[ID] = value; }
		}
	}

	public struct BLOB
	{
		byte[] value;

		BLOB(byte[] value)
		{
			this.value = value;
		}

		public static implicit operator byte[](BLOB value)
		{
			return value.value;
		}

		public static implicit operator BLOB(byte[] value)
		{
			byte[] tvalue = (byte[])value;
			return new BLOB(tvalue);
		}

		public Byte this[int ID]
		{
			get { return value[ID]; }
			set { this.value[ID] = value; }
		}
	}

	public struct VECTOR2
	{
		Vector2 value;

		VECTOR2(Vector2 value)
		{
			this.value = value;
		}

		public static implicit operator Vector2(VECTOR2 value)
		{
			return value.value;
		}

		public static implicit operator VECTOR2(Vector2 value)
		{
			Vector2 tvalue = (Vector2)value;
			return new VECTOR2(tvalue);
		}

		public float x
		{
			get { return value.x; }
			set { this.value.x = value; }
		}

		public float y
		{
			get { return value.y; }
			set { this.value.y = value; }
		}

	}

	public struct VECTOR3
	{
		Vector3 value;

		VECTOR3(Vector3 value)
		{
			this.value = value;
		}

		public static implicit operator Vector3(VECTOR3 value)
		{
			return value.value;
		}

		public static implicit operator VECTOR3(Vector3 value)
		{
			Vector3 tvalue = (Vector3)value;
			return new VECTOR3(tvalue);
		}

		public float x
		{
			get { return value.x; }
			set { this.value.x = value; }
		}

		public float y
		{
			get { return value.y; }
			set { this.value.y = value; }
		}

		public float z
		{
			get { return value.z; }
			set { this.value.z = value; }
		}

	}

	public struct VECTOR4
	{
		Vector4 value;

		VECTOR4(Vector4 value)
		{
			this.value = value;
		}

		public static implicit operator Vector4(VECTOR4 value)
		{
			return value.value;
		}

		public static implicit operator VECTOR4(Vector4 value)
		{
			Vector4 tvalue = (Vector4)value;
			return new VECTOR4(tvalue);
		}

		public float x
		{
			get { return value.x; }
			set { this.value.x = value; }
		}

		public float y
		{
			get { return value.y; }
			set { this.value.y = value; }
		}

		public float z
		{
			get { return value.z; }
			set { this.value.z = value; }
		}

		public float w
		{
			get { return value.w; }
			set { this.value.w = value; }
		}
	}

	public struct ACCOUNT_ID
	{
		UInt64 value;

		ACCOUNT_ID(UInt64 value)
		{
			this.value = value;
		}

		public static implicit operator UInt64(ACCOUNT_ID value)
		{
			return value.value;
		}

		public static implicit operator ACCOUNT_ID(UInt64 value)
		{
			UInt64 tvalue = (UInt64)value;
			return new ACCOUNT_ID(tvalue);
		}

		public static UInt64 MaxValue
		{
			get
			{
				return UInt64.MaxValue;
			}
		}

		public static UInt64 MinValue
		{
			get
			{
				return UInt64.MinValue;
			}
		}
	}

	public struct BOOL
	{
		Byte value;

		BOOL(Byte value)
		{
			this.value = value;
		}

		public static implicit operator Byte(BOOL value)
		{
			return value.value;
		}

		public static implicit operator BOOL(Byte value)
		{
			Byte tvalue = (Byte)value;
			return new BOOL(tvalue);
		}

		public static Byte MaxValue
		{
			get
			{
				return Byte.MaxValue;
			}
		}

		public static Byte MinValue
		{
			get
			{
				return Byte.MinValue;
			}
		}
	}

	public struct ITEM_ID
	{
		Int32 value;

		ITEM_ID(Int32 value)
		{
			this.value = value;
		}

		public static implicit operator Int32(ITEM_ID value)
		{
			return value.value;
		}

		public static implicit operator ITEM_ID(Int32 value)
		{
			Int32 tvalue = (Int32)value;
			return new ITEM_ID(tvalue);
		}

		public static Int32 MaxValue
		{
			get
			{
				return Int32.MaxValue;
			}
		}

		public static Int32 MinValue
		{
			get
			{
				return Int32.MinValue;
			}
		}
	}

	public struct ITEMTYPE
	{
		Int32 value;

		ITEMTYPE(Int32 value)
		{
			this.value = value;
		}

		public static implicit operator Int32(ITEMTYPE value)
		{
			return value.value;
		}

		public static implicit operator ITEMTYPE(Int32 value)
		{
			Int32 tvalue = (Int32)value;
			return new ITEMTYPE(tvalue);
		}

		public static Int32 MaxValue
		{
			get
			{
				return Int32.MaxValue;
			}
		}

		public static Int32 MinValue
		{
			get
			{
				return Int32.MinValue;
			}
		}
	}

	public struct DBID
	{
		UInt64 value;

		DBID(UInt64 value)
		{
			this.value = value;
		}

		public static implicit operator UInt64(DBID value)
		{
			return value.value;
		}

		public static implicit operator DBID(UInt64 value)
		{
			UInt64 tvalue = (UInt64)value;
			return new DBID(tvalue);
		}

		public static UInt64 MaxValue
		{
			get
			{
				return UInt64.MaxValue;
			}
		}

		public static UInt64 MinValue
		{
			get
			{
				return UInt64.MinValue;
			}
		}
	}

	public struct UID
	{
		string value;

		UID(string value)
		{
			this.value = value;
		}

		public static implicit operator string(UID value)
		{
			return value.value;
		}

		public static implicit operator UID(string value)
		{
			string tvalue = (string)value;
			return new UID(tvalue);
		}
	}

	public struct ENTITY_ID
	{
		Int32 value;

		ENTITY_ID(Int32 value)
		{
			this.value = value;
		}

		public static implicit operator Int32(ENTITY_ID value)
		{
			return value.value;
		}

		public static implicit operator ENTITY_ID(Int32 value)
		{
			Int32 tvalue = (Int32)value;
			return new ENTITY_ID(tvalue);
		}

		public static Int32 MaxValue
		{
			get
			{
				return Int32.MaxValue;
			}
		}

		public static Int32 MinValue
		{
			get
			{
				return Int32.MinValue;
			}
		}
	}

	public struct ENTITY_NO
	{
		UInt32 value;

		ENTITY_NO(UInt32 value)
		{
			this.value = value;
		}

		public static implicit operator UInt32(ENTITY_NO value)
		{
			return value.value;
		}

		public static implicit operator ENTITY_NO(UInt32 value)
		{
			UInt32 tvalue = (UInt32)value;
			return new ENTITY_NO(tvalue);
		}

		public static UInt32 MaxValue
		{
			get
			{
				return UInt32.MaxValue;
			}
		}

		public static UInt32 MinValue
		{
			get
			{
				return UInt32.MinValue;
			}
		}
	}

	public struct ENTITY_UTYPE
	{
		UInt32 value;

		ENTITY_UTYPE(UInt32 value)
		{
			this.value = value;
		}

		public static implicit operator UInt32(ENTITY_UTYPE value)
		{
			return value.value;
		}

		public static implicit operator ENTITY_UTYPE(UInt32 value)
		{
			UInt32 tvalue = (UInt32)value;
			return new ENTITY_UTYPE(tvalue);
		}

		public static UInt32 MaxValue
		{
			get
			{
				return UInt32.MaxValue;
			}
		}

		public static UInt32 MinValue
		{
			get
			{
				return UInt32.MinValue;
			}
		}
	}

	public struct ERR_MSG
	{
		string value;

		ERR_MSG(string value)
		{
			this.value = value;
		}

		public static implicit operator string(ERR_MSG value)
		{
			return value.value;
		}

		public static implicit operator ERR_MSG(string value)
		{
			string tvalue = (string)value;
			return new ERR_MSG(tvalue);
		}
	}

	public class CARD_GROUP : List<List<UInt64>>
	{

	}

	public class CARD_GROUP_IN : List<UInt64>
	{

	}

	public class ENTITY_ID_LIST : List<Int32>
	{

	}

	public class AVATAR_CARDLIST : List<UInt64>
	{

	}

	public class ENTITY_LIST : List<byte[]>
	{

	}

	public class ACCOUNT_DATA
	{
		public UInt64 money = 0;
		public UInt64 diamond = 0;
		public UInt64 kglod = 0;
		public UInt64 eglod = 0;
		public string name = "";
		public Byte gender = 0;
		public UInt32 Icon = 0;
		public Byte FirstLogin = 0;
		public Byte FirstRecharge = 0;
		public UInt64 rank = 0;

	}

	public class STEAL_LIST : List<UInt64>
	{

	}

	public class LAND_INFO
	{
		public UInt32 ID = 0;
		public UInt32 LandType = 0;
		public UInt32 ItemType = 0;
		public UInt32 UseNum = 0;
		public UInt32 stage = 0;
		public UInt32 EndTime = 0;
		public UInt32 surpHarvest = 0;
		public UInt32 Harvest = 0;
		public STEAL_LIST StealList = new STEAL_LIST();

	}

	public class LAND_LIST : List<LAND_INFO>
	{

	}

	public class GJ_INFO
	{
		public UInt32 GJType = 0;
		public UInt64 GJEndtime = 0;
		public UInt64 GJGetEndtime = 0;

	}

	public class FRIEND_INFO
	{
		public string uid = "";
		public Byte online = 0;
		public UInt64 DBID = 0;
		public string Name = "";
		public UInt32 Icon = 0;
		public Byte gender = 0;
		public Byte CanSteal = 0;

	}

	public class APPLY_INFO
	{
		public UInt64 DBID = 0;
		public Byte IsYao = 0;

	}

	public class ACCEPT_INFO
	{
		public UInt64 DBID = 0;
		public UInt64 YaoEndTime = 0;

	}

	public class STEAL_INFO
	{
		public UInt32 LandID = 0;
		public UInt32 StealValue = 0;

	}

	public class CAN_STEAL_INFO
	{
		public UInt64 DBID = 0;
		public Byte CanSteal = 0;

	}

	public class ITEM_INFO
	{
		public Int32 ItemType = 0;
		public UInt32 ItemNum = 0;

	}

	public class SYS_MESSAGE
	{
		public UInt64 MesaageUUID = 0;
		public UInt64 time = 0;
		public UInt32 MesaageID = 0;
		public List<string> ArgList = new List<string>();

	}

	public class PET_MAP_CONFIG_INFO
	{
		public string cityName = "";
		public string position = "";
		public string location = "";
		public string radius = "";
		public string Scycle = "";
		public string Ecycle = "";
		public string Stime = "";
		public string Etime = "";
		public string frequence = "";
		public string gen_min = "";
		public string gen_max = "";
		public string gen_id = "";
		public string spe_min = "";
		public string spe_max = "";
		public string spe_id = "";
		public string spe_prob = "";
		public string spe_prob_list = "";
		public string enable = "";

	}

	public class PET_MAP_XYZ
	{
		public UInt32 PetType = 0;
		public UInt32 PetNum = 0;

	}

	public class PET_MAP_INFO
	{
		public string cityName = "";
		public string position = "";
		public UInt32 radius = 0;
		public UInt64 refreshEndTime = 0;
		public List<PET_MAP_XYZ> PetXYZList = new List<PET_MAP_XYZ>();

	}

	public class PET_SELF_INFO
	{
		public UInt32 radius = 0;
		public UInt64 refreshEndTime = 0;
		public List<PET_MAP_XYZ> PetXYZList = new List<PET_MAP_XYZ>();

	}

	public class PET_INFO
	{
		public UInt64 UUID = 0;
		public UInt32 PetType = 0;
		public UInt64 Endtime = 0;

	}

	public class TASK_INFO
	{
		public UInt32 TaskType = 0;
		public UInt32 FinishNum = 0;
		public UInt32 CanAward = 0;
		public UInt64 Endtime = 0;

	}

	public class CARD_INFOS_LIST
	{
		public List<UInt64> values = new List<UInt64>();

	}

	public class OPEN_PACK_DATA
	{
		public UInt64 card1 = 0;
		public UInt64 card2 = 0;
		public UInt64 card3 = 0;
		public UInt64 card4 = 0;
		public UInt64 card5 = 0;

	}

	public class OPEN_PACK_NAME_DATA
	{
		public string card1 = "";
		public string card2 = "";
		public string card3 = "";
		public string card4 = "";
		public string card5 = "";

	}

	public class AVATAR_INFOS
	{
		public string name = "";
		public Byte roleType = 0;
		public AVATAR_CARDLIST cardList = new AVATAR_CARDLIST();

	}

	public class STR_LIST : List<string>
	{

	}

	public class AVATAR_INFOS_LIST : List<AVATAR_INFOS>
	{

	}

	public class LLSTRING : List<List<string>>
	{

	}

	public class OnlinePlayerData : List<byte[]>
	{

	}

	public class CARD_DATA
	{
		public List<UInt64> value = new List<UInt64>();

	}


}